spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/libraryDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
